#!/bin/sh
rm modules/FvwmAudio/FvwmAudio
rm modules/FvwmBacker/FvwmBacker
rm modules/FvwmBanner/FvwmBanner
rm modules/FvwmClean/FvwmClean
rm modules/FvwmDebug/FvwmDebug
rm modules/FvwmIconBox/FvwmIconBox
rm modules/FvwmIdent/FvwmIdent
rm modules/FvwmPager/FvwmPager
rm modules/FvwmSave/FvwmSave
rm modules/FvwmSaveDesk/FvwmSaveDesk
rm modules/FvwmScroll/FvwmScroll
rm modules/FvwmWinList/FvwmWinList
rm modules/FvwmAuto/FvwmAuto
rm modules/GoodStuff/GoodStuff
rm fvwm/fvwm
rm xpmroot/xpmroot
rm libs/*.a
rm -f *.o 
rm -f *~ 
rm -f *.bak 
rm -f *.orig 
rm -f *.rej 
rm -f Makefile 
rm -f core 
rm -f #*#
rm -f */*.o 
rm -f */*~ 
rm -f */*.bak 
rm -f */*.orig 
rm -f */*.rej 
rm -f */Makefile 
rm -f */core 
rm -f */#*#
rm -f */*/*.o 
rm -f */*/*~ 
rm -f */*/*.bak 
rm -f */*/*.orig 
rm -f */*/*.rej 
rm -f */*/Makefile 
rm -f */*/core 
rm -f */*/#*#




